# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0002_auto_20170926_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='poster',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post_messages', to='dashapp.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dashapp.User'),
        ),
    ]
